### ISSUE TITLE
Is this still valid and useful information? If so can we copy into the current CDE repo and if not archive this?

### ISSUE THREAD

**Issue by steviewanders** [HakaiInstitute/cioos-data-explorer#3]
🙂

**Comment by n-a-t-e** [comment]
This repo exists exclusively for it's Wiki - https://github.com/HakaiInstitute/cioos-data-explorer/wiki . It tells data providers how to setup their ERDDAP datasets to be ingested by CDE.

Maybe there's a better spot for this information, the CDE repo being private, and the wiki information in this repo needing to be public

**Comment by steviewanders** [comment]
Don't mind it staying here until a better spot is found. 

Until then can we rename the repo title since that was unknown to me and likely everyone else.
So, `<name>-public-wiki` and update wherever it is linked from.

**Comment by steviewanders** [comment]
To be moved when CDE is to CIOOS ownership
